### ISSUE TITLE
"application.js isn't precompiled" on preview

### ISSUE THREAD

**Issue by gtrogers** [alphagov/transaction-wrappers#20]
This error started happening on preview when we deployed the latest version of the app with the performance platform tracking code.

I imagine this is because the asset pipeline isn't set up correctly but will take a closer look tomorrow.

**Comment by alext** [comment]
Transaction-wrappers hasn't been setup to have its own assets at the moment.  It needs relevant bits added both to alphagov-deployment, and to puppet.

I can take a look at this.

**Comment by alext** [comment]
Fixed in 3 pull requests (puppet#654, alphagov-deployment#189 and alphagov/transaction-wrappers#21)

**Comment by gtrogers** [comment]
Many thanks. :+1:
